package com.aaronsedna.hopecards.model

/**
 * Converts a stable English reference into the book-title form used by its Bible edition.
 *
 * The canonical reference remains unchanged in verse assets, favourites, journals, Daily Hope,
 * and backups. Only presentation text is localized, so existing saved data remains compatible.
 */
object BibleReferenceFormatter {
    private val referencePattern = Regex("^(.+?)\\s+(\\d+:\\d+(?:[-–]\\d+)?)$")

    fun format(reference: String, translation: Translation): String {
        if (translation.language == "English") return reference

        val match = referencePattern.matchEntire(reference.trim()) ?: return reference
        val canonicalBook = canonicalBook(match.groupValues[1])
        val book = compactBookTitles[translation]?.get(canonicalBook)
            ?: bookTitles[translation]?.get(canonicalBook)
            ?: return reference
        return "$book ${match.groupValues[2]}"
    }

    internal fun hasLocalizedBookTitle(reference: String, translation: Translation): Boolean {
        if (translation.language == "English") return true
        val match = referencePattern.matchEntire(reference.trim()) ?: return false
        val canonicalBook = canonicalBook(match.groupValues[1])
        return compactBookTitles[translation]?.containsKey(canonicalBook) == true ||
            bookTitles[translation]?.containsKey(canonicalBook) == true
    }

    private fun canonicalBook(book: String): String = if (book == "Psalm") "Psalms" else book

    private val compactBookTitles = mapOf(
        Translation.LUT1912 to mapOf(
            "Acts" to "Apg",
            "1 Thessalonians" to "1 Thess",
            "2 Thessalonians" to "2 Thess",
        ),
        Translation.LSG1910 to mapOf(
            "1 Thessalonians" to "1 Th",
            "2 Thessalonians" to "2 Th",
        ),
        Translation.RIV1927 to mapOf(
            "1 Thessalonians" to "1 Tess.",
            "2 Thessalonians" to "2 Tess.",
        ),
        Translation.RV1909 to mapOf(
            "1 Thessalonians" to "1 Tes.",
            "2 Thessalonians" to "2 Tes.",
        ),
        Translation.ADB1905 to mapOf(
            "1 Corinthians" to "1 Cor.",
            "2 Corinthians" to "2 Cor.",
            "1 Thessalonians" to "1 Tes.",
            "2 Thessalonians" to "2 Tes.",
        ),
        Translation.MAL1910 to mapOf(
            "Acts" to "അപ്പൊ. പ്രവൃത്തികൾ",
            "1 Thessalonians" to "1. തെസ്സ.",
            "2 Thessalonians" to "2. തെസ്സ.",
        ),
    )

    private val bookTitles = mapOf(
        Translation.LUT1912 to mapOf(
            "Genesis" to "1. Mose",
            "Exodus" to "2. Mose",
            "Numbers" to "4. Mose",
            "Deuteronomy" to "5. Mose",
            "Joshua" to "Josua",
            "1 Samuel" to "1. Samuel",
            "2 Samuel" to "2. Samuel",
            "1 Chronicles" to "1. Chronik",
            "Nehemiah" to "Nehemia",
            "Job" to "Hiob",
            "Psalms" to "Psalmen",
            "Proverbs" to "Sprüche",
            "Isaiah" to "Jesaja",
            "Jeremiah" to "Jeremia",
            "Lamentations" to "Klagelieder",
            "Daniel" to "Daniel",
            "Micah" to "Micha",
            "Nahum" to "Nahum",
            "Habakkuk" to "Habakuk",
            "Matthew" to "Matthäus",
            "Mark" to "Markus",
            "Luke" to "Lukas",
            "John" to "Johannes",
            "Acts" to "Apostelgeschichte",
            "Romans" to "Römer",
            "1 Corinthians" to "1. Korinther",
            "2 Corinthians" to "2. Korinther",
            "Galatians" to "Galater",
            "Ephesians" to "Epheser",
            "Philippians" to "Philipper",
            "Colossians" to "Kolosser",
            "1 Thessalonians" to "1. Thessalonicher",
            "2 Thessalonians" to "2. Thessalonicher",
            "1 Timothy" to "1. Timotheus",
            "2 Timothy" to "2. Timotheus",
            "Philemon" to "Philemon",
            "Hebrews" to "Hebräer",
            "James" to "Jakobus",
            "1 Peter" to "1. Petrus",
            "2 Peter" to "2. Petrus",
            "1 John" to "1. Johannes",
            "2 John" to "2. Johannes",
            "Jude" to "Judas",
            "Revelation" to "Offenbarung",
        ),
        Translation.LSG1910 to mapOf(
            "Genesis" to "Genèse",
            "Exodus" to "Exode",
            "Numbers" to "Nombres",
            "Deuteronomy" to "Deutéronome",
            "Joshua" to "Josué",
            "1 Samuel" to "1 Samuel",
            "2 Samuel" to "2 Samuel",
            "1 Chronicles" to "1 Chroniques",
            "Nehemiah" to "Néhémie",
            "Job" to "Job",
            "Psalms" to "Psaumes",
            "Proverbs" to "Proverbes",
            "Isaiah" to "Ésaïe",
            "Jeremiah" to "Jérémie",
            "Lamentations" to "Lamentations",
            "Daniel" to "Daniel",
            "Micah" to "Michée",
            "Nahum" to "Nahum",
            "Habakkuk" to "Habacuc",
            "Matthew" to "Matthieu",
            "Mark" to "Marc",
            "Luke" to "Luc",
            "John" to "Jean",
            "Acts" to "Actes",
            "Romans" to "Romains",
            "1 Corinthians" to "1 Corinthiens",
            "2 Corinthians" to "2 Corinthiens",
            "Galatians" to "Galates",
            "Ephesians" to "Éphésiens",
            "Philippians" to "Philippiens",
            "Colossians" to "Colossiens",
            "1 Thessalonians" to "1 Thessaloniciens",
            "2 Thessalonians" to "2 Thessaloniciens",
            "1 Timothy" to "1 Timothée",
            "2 Timothy" to "2 Timothée",
            "Philemon" to "Philémon",
            "Hebrews" to "Hébreux",
            "James" to "Jacques",
            "1 Peter" to "1 Pierre",
            "2 Peter" to "2 Pierre",
            "1 John" to "1 Jean",
            "2 John" to "2 Jean",
            "Jude" to "Jude",
            "Revelation" to "Apocalypse",
        ),
        Translation.RIV1927 to mapOf(
            "Genesis" to "Genesi",
            "Exodus" to "Esodo",
            "Numbers" to "Numeri",
            "Deuteronomy" to "Deuteronomio",
            "Joshua" to "Giosuè",
            "1 Samuel" to "1 Samuele",
            "2 Samuel" to "2 Samuele",
            "1 Chronicles" to "1 Cronache",
            "Nehemiah" to "Neemia",
            "Job" to "Giobbe",
            "Psalms" to "Salmi",
            "Proverbs" to "Proverbi",
            "Isaiah" to "Isaia",
            "Jeremiah" to "Geremia",
            "Lamentations" to "Lamentazioni",
            "Daniel" to "Daniele",
            "Micah" to "Michea",
            "Nahum" to "Nahum",
            "Habakkuk" to "Abacuc",
            "Matthew" to "Matteo",
            "Mark" to "Marco",
            "Luke" to "Luca",
            "John" to "Giovanni",
            "Acts" to "Atti",
            "Romans" to "Romani",
            "1 Corinthians" to "1 Corinti",
            "2 Corinthians" to "2 Corinti",
            "Galatians" to "Galati",
            "Ephesians" to "Efesini",
            "Philippians" to "Filippesi",
            "Colossians" to "Colossesi",
            "1 Thessalonians" to "1 Tessalonicesi",
            "2 Thessalonians" to "2 Tessalonicesi",
            "1 Timothy" to "1 Timoteo",
            "2 Timothy" to "2 Timoteo",
            "Philemon" to "Filemone",
            "Hebrews" to "Ebrei",
            "James" to "Giacomo",
            "1 Peter" to "1 Pietro",
            "2 Peter" to "2 Pietro",
            "1 John" to "1 Giovanni",
            "2 John" to "2 Giovanni",
            "Jude" to "Giuda",
            "Revelation" to "Apocalisse",
        ),
        Translation.RV1909 to mapOf(
            "Genesis" to "Génesis",
            "Exodus" to "Éxodo",
            "Numbers" to "Números",
            "Deuteronomy" to "Deuteronomio",
            "Joshua" to "Josué",
            "1 Samuel" to "1 Samuel",
            "2 Samuel" to "2 Samuel",
            "1 Chronicles" to "1 Crónicas",
            "Nehemiah" to "Nehemías",
            "Job" to "Job",
            "Psalms" to "Salmos",
            "Proverbs" to "Proverbios",
            "Isaiah" to "Isaías",
            "Jeremiah" to "Jeremías",
            "Lamentations" to "Lamentaciones",
            "Daniel" to "Daniel",
            "Micah" to "Miqueas",
            "Nahum" to "Nahum",
            "Habakkuk" to "Habacuc",
            "Matthew" to "San Mateo",
            "Mark" to "Marcos",
            "Luke" to "San Lucas",
            "John" to "Juan",
            "Acts" to "Hechos",
            "Romans" to "Romanos",
            "1 Corinthians" to "1 Corintios",
            "2 Corinthians" to "2 Corintios",
            "Galatians" to "Gálatas",
            "Ephesians" to "Efesios",
            "Philippians" to "Filipenses",
            "Colossians" to "Colosenses",
            "1 Thessalonians" to "1 Tesalonicenses",
            "2 Thessalonians" to "2 Tesalonicenses",
            "1 Timothy" to "1 Timoteo",
            "2 Timothy" to "2 Timoteo",
            "Philemon" to "Filemón",
            "Hebrews" to "Hebreos",
            "James" to "Santiago",
            "1 Peter" to "1 Pedro",
            "2 Peter" to "2 Pedro",
            "1 John" to "1 Juan",
            "2 John" to "2 Juan",
            "Jude" to "Judas",
            "Revelation" to "Apocalipsis",
        ),
        Translation.ADB1905 to mapOf(
            "Genesis" to "Genesis",
            "Exodus" to "Exodo",
            "Numbers" to "Mga Bilang",
            "Deuteronomy" to "Deuteronomio",
            "Joshua" to "Josue",
            "1 Samuel" to "1 Samuel",
            "2 Samuel" to "2 Samuel",
            "1 Chronicles" to "1 Mga Cronica",
            "Nehemiah" to "Nehemias",
            "Job" to "Job",
            "Psalms" to "Mga Awit",
            "Proverbs" to "Mga Kawikaan",
            "Isaiah" to "Isaias",
            "Jeremiah" to "Jeremias",
            "Lamentations" to "Mga Panaghoy",
            "Daniel" to "Daniel",
            "Micah" to "Mikas",
            "Nahum" to "Nahum",
            "Habakkuk" to "Habakkuk",
            "Matthew" to "Mateo",
            "Mark" to "Marcos",
            "Luke" to "Lucas",
            "John" to "Juan",
            "Acts" to "Mga Gawa",
            "Romans" to "Mga Taga-Roma",
            "1 Corinthians" to "1 Mga Taga-Corinto",
            "2 Corinthians" to "2 Mga Taga-Corinto",
            "Galatians" to "Mga Taga-Galacia",
            "Ephesians" to "Mga Taga-Efeso",
            "Philippians" to "Mga Taga-Filipos",
            "Colossians" to "Mga Taga-Colosas",
            "1 Thessalonians" to "1 Mga Taga-Tesalonica",
            "2 Thessalonians" to "2 Mga Taga-Tesalonica",
            "1 Timothy" to "1 Timoteo",
            "2 Timothy" to "2 Timoteo",
            "Philemon" to "Filemon",
            "Hebrews" to "Mga Hebreo",
            "James" to "Santiago",
            "1 Peter" to "1 Pedro",
            "2 Peter" to "2 Pedro",
            "1 John" to "1 Juan",
            "2 John" to "2 Juan",
            "Jude" to "Judas",
            "Revelation" to "Pahayag",
        ),
        Translation.MAL1910 to mapOf(
            "Genesis" to "ഉല്പത്തി",
            "Exodus" to "പുറപ്പാടു",
            "Numbers" to "സംഖ്യാപുസ്തകം",
            "Deuteronomy" to "ആവർത്തനപുസ്തകം",
            "Joshua" to "യോശുവ",
            "1 Samuel" to "1. ശമൂവേൽ",
            "2 Samuel" to "2. ശമൂവേൽ",
            "1 Chronicles" to "1. ദിനവൃത്താന്തം",
            "Nehemiah" to "നെഹെമ്യാവു",
            "Job" to "ഇയ്യോബ്",
            "Psalms" to "സങ്കീർത്തനങ്ങൾ",
            "Proverbs" to "സദൃശവാക്യങ്ങൾ",
            "Isaiah" to "യെശയ്യാവു",
            "Jeremiah" to "യിരെമ്യാവു",
            "Lamentations" to "വിലാപങ്ങൾ",
            "Daniel" to "ദാനീയേൽ",
            "Micah" to "മീഖാ",
            "Nahum" to "നഹൂം",
            "Habakkuk" to "ഹബക്കൂൿ",
            "Matthew" to "മത്തായി",
            "Mark" to "മർക്കൊസ്",
            "Luke" to "ലൂക്കൊസ്",
            "John" to "യോഹന്നാൻ",
            "Acts" to "അപ്പൊസ്തലന്മാരുടെ പ്രവൃത്തികൾ",
            "Romans" to "റോമർ",
            "1 Corinthians" to "1. കൊരിന്ത്യർ",
            "2 Corinthians" to "2. കൊരിന്ത്യർ",
            "Galatians" to "ഗലാത്യർ",
            "Ephesians" to "എഫെസ്യർ",
            "Philippians" to "ഫിലിപ്പിയർ",
            "Colossians" to "കൊലൊസ്സ്യർ",
            "1 Thessalonians" to "1. തെസ്സലൊനീക്യർ",
            "2 Thessalonians" to "2. തെസ്സലൊനീക്യർ",
            "1 Timothy" to "1. തിമൊഥെയൊസ്",
            "2 Timothy" to "2. തിമൊഥെയൊസ്",
            "Philemon" to "ഫിലേമോൻ",
            "Hebrews" to "എബ്രായർ",
            "James" to "യാക്കോബ്",
            "1 Peter" to "1. പത്രൊസ്",
            "2 Peter" to "2. പത്രൊസ്",
            "1 John" to "1. യോഹന്നാൻ",
            "2 John" to "2. യോഹന്നാൻ",
            "Jude" to "യൂദാ",
            "Revelation" to "വെളിപ്പാടു",
        ),
    )
}
